spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: Owl842651
  activiti:
    history-level: full
    db-history-used: true
    check-process-definitions: false

mybatis:
  mapper-locations: com.example.workflow.mapper/*.xml
  type-aliases-package: com.example.workflow.model



